export interface LanguageValues {
    LANGUAGE_ENABLED: {};
    LANGUAGE_ID: {};
    LANGUAGE_NAME: {};
    CREATE_INSTANT_INVITE: {};
    KICK_MEMBERS: {};
    BAN_MEMBERS: {};
    ADMINISTRATOR: {};
    MANAGE_CHANNELS: {};
    MANAGE_GUILD: {};
    ADD_REACTIONS: {};
    VIEW_AUDIT_LOG: {};
    PRIORITY_SPEAKER: {};
    STREAM: {};
    VIEW_CHANNEL: {};
    SEND_MESSAGES: {};
    SEND_TTS_MESSAGES: {};
    MANAGE_MESSAGES: {};
    EMBED_LINKS: {};
    ATTACH_FILES: {};
    READ_MESSAGE_HISTORY: {};
    MENTION_EVERYONE: {};
    USE_EXTERNAL_EMOJIS: {};
    VIEW_GUILD_INSIGHTS: {};
    CONNECT: {};
    SPEAK: {};
    MUTE_MEMBERS: {};
    DEAFEN_MEMBERS: {};
    MOVE_MEMBERS: {};
    USE_VAD: {};
    CHANGE_NICKNAME: {};
    MANAGE_NICKNAMES: {};
    MANAGE_ROLES: {};
    MANAGE_WEBHOOKS: {};
    MANAGE_EMOJIS_AND_STICKERS: {};
    USE_APPLICATION_COMMANDS: {};
    REQUEST_TO_SPEAK: {};
    MANAGE_EVENTS: {};
    MANAGE_THREADS: {};
    CREATE_PUBLIC_THREADS: {};
    CREATE_PRIVATE_THREADS: {};
    USE_EXTERNAL_STICKERS: {};
    SEND_MESSAGES_IN_THREADS: {};
    USE_EMBEDDED_ACTIVITIES: {};
    MODERATE_MEMBERS: {};
    PARSE_REGEX: {};
    MS_OTHER: {};
    SECOND_ONE: {};
    SECOND_OTHER: {};
    SECOND_SHORT: {};
    MINUTE_ONE: {};
    MINUTE_OTHER: {};
    MINUTE_SHORT: {};
    HOUR_ONE: {};
    HOUR_OTHER: {};
    HOUR_SHORT: {};
    DAY_ONE: {};
    DAY_OTHER: {};
    DAY_SHORT: {};
    YEAR_ONE: {};
    YEAR_OTHER: {};
    YEAR_SHORT: {};
    MISSING_PERMISSIONS_BASE_TITLE: {};
    MISSING_PERMISSIONS_GUILD_ONLY: { type: any };
    MISSING_PERMISSIONS_OWNER_ONLY: { type: any };
    MISSING_PERMISSIONS_DEVELOPER_ONLY: { type: any };
    MISSING_PERMISSIONS_USER_PERMISSIONS_ONE: {
        missingPermissions: any;
        type: any;
    };
    MISSING_PERMISSIONS_USER_PERMISSIONS_OTHER: {
        missingPermissions: any;
        type: any;
    };
    MISSING_PERMISSIONS_CLIENT_PERMISSIONS_ONE: {
        missingPermissions: any;
        type: any;
    };
    MISSING_PERMISSIONS_CLIENT_PERMISSIONS_OTHER: {
        missingPermissions: any;
        type: any;
    };
    TYPE_ON_COOLDOWN_TITLE: { type: any };
    TYPE_ON_COOLDOWN_DESCRIPTION: { type: any; formattedTime: any };
    NON_EXISTENT_TITLE: { type: any };
    NON_EXISTENT_DESCRIPTION: { type: any; name: any; username: any };
    COOLDOWN_ON_TYPE_TITLE: { type: any };
    COOLDOWN_ON_TYPE_DESCRIPTION: { type: any };
    AN_ERROR_HAS_OCCURRED_TITLE: {};
    AN_ERROR_HAS_OCCURRED_DESCRIPTION: { type: any; name: any };
    AN_ERROR_HAS_OCCURRED_DESCRIPTION_NO_NAME: { type: any };
    PING: {};
    PONG: { roundTrip: any; hostLatency: any; apiLatency: any };
    LANGUAGE_SET_TITLE: {};
    LANGUAGE_SET_DESCRIPTION: { language: any };
    INVALID_INTERACTION_TITLE: {};
    INVALID_INTERACTION_DESCRIPTION: {};
    ACTION_LOG_SET_TITLE: {};
    ACTION_LOG_SET_DESCRIPTION: { actionLogChannel: any };
    ACTION_LOG_REMOVED_TITLE: {};
    ACTION_LOG_REMOVED_DESCRIPTION: {};
}
